export const ADMIN_SIGNIN_REQUEST="ADMIN_SIGNIN_REQUEST"
export const ADMIN_SIGNIN_SUCCESS="ADMIN_SIGNIN_SUCCESS"
export const ADMIN_SIGNIN_FAIL="ADMIN_SIGNIN_FAIL"




export const ADMIN_REGISTER_REQUEST="ADMIN_REGISTER_REQUEST"
export const ADMIN_REGISTER_SUCCESS="ADMIN_REGISTER_SUCCESS"
export const ADMIN_REGISTER_FAIL="ADMIN_REGISTER_FAIL"



export const ADMIN_SIGNOUT="ADMIN_SIGNOUT"


export const ADMIN_DETAILS_REQUEST="ADMIN_DETAILS_REQUEST"
export const ADMIN_DETAILS_SUCCESS="ADMIN_DETAILS_SUCCESS"
export const ADMIN_DETAILS_FAIL="ADMIN_DETAILS_FAIL"

export const GET_ADMINS_REQUEST="GET_ADMINS_REQUEST"
export const GET_ADMINS_SUCCESS="GET_ADMINS_SUCCESS"
export const GET_ADMINS_FAIL="GET_ADMINS_FAIL"
