export const CASHIER_SIGNIN_REQUEST="CASHIER_SIGNIN_REQUEST"
export const CASHIER_SIGNIN_SUCCESS="CASHIER_SIGNIN_SUCCESS"
export const CASHIER_SIGNIN_FAIL="CASHIER_SIGNIN_FAIL"




export const CASHIER_REGISTER_REQUEST="CASHIER_REGISTER_REQUEST"
export const CASHIER_REGISTER_SUCCESS="CASHIER_REGISTER_SUCCESS"
export const CASHIER_REGISTER_FAIL="CASHIER_REGISTER_FAIL"



export const CASHIER_SIGNOUT="CASHIER_SIGNOUT"


export const CASHIER_DETAILS_REQUEST="CASHIER_DETAILS_REQUEST"
export const CASHIER_DETAILS_SUCCESS="CASHIER_DETAILS_SUCCESS"
export const CASHIER_DETAILS_FAIL="CASHIER_DETAILS_FAIL"


