export const GET_PRODUCTS_REQUEST="GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL="GET_PRODUCTS_FAIL";


export const GET_PRODUCT_REQUEST="GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL="GET_PRODUCT_FAIL";



export const CREATE_PRODUCT_REQUEST="CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS="CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL="CREATE_PRODUCT_FAIL";

export const UPDATE_PRODUCT_REQUEST="UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS="UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL="UPDATE_PRODUCT_FAIL";


export const DELETE_PRODUCT_REQUEST="DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL="DELETE_PRODUCT_FAIL";

